// Real pointer-input test: pick Roads, click twice on the canvas, zone, run.
import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const logs = [];
page.on('pageerror', (e) => logs.push('pageerror ' + e.message));
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('CERT') && !m.text().includes('404')) logs.push(m.text()); });
await page.goto('http://127.0.0.1:5173/#skip&map=appalachia&mode=sandbox', { waitUntil: 'load' });
await page.waitForTimeout(7000);
const segs = () => page.evaluate(() => window.__game.net.segs.size);
console.log('segs start', await segs());
await page.click('button.tbtn[data-t="roads"]');
await page.waitForTimeout(300);
await page.click('button.card[data-road="stroad4"]');
await page.mouse.move(520, 300); await page.waitForTimeout(200);
await page.mouse.click(520, 300); await page.waitForTimeout(400);
await page.mouse.move(840, 260); await page.waitForTimeout(400);
await page.mouse.click(840, 260); await page.waitForTimeout(600);
await page.keyboard.press('Escape');
console.log('segs after road', await segs());
await page.click('button.tbtn[data-t="zones"]');
await page.waitForTimeout(200);
await page.click('button.card[data-zone="comLow"]');
await page.mouse.move(660, 290);
await page.mouse.down(); await page.mouse.move(700, 300, { steps: 6 }); await page.mouse.move(760, 280, { steps: 6 }); await page.mouse.up();
await page.waitForTimeout(300);
console.log('zoned', await page.evaluate(() => JSON.stringify(window.__game.zones.counts().zoned)));
await page.keyboard.press('Escape');
await page.keyboard.press('3');
await page.waitForTimeout(8000);
console.log('bld', await page.evaluate(() => window.__game.buildings.list.size));
await page.screenshot({ path: 'shots/interact.png' });
console.log(logs.join('\n'));
await browser.close();
