import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errs = [];
page.on('pageerror', (e) => errs.push(e.message));
await page.goto('http://127.0.0.1:5173/#skip&map=norcal&mode=ponzi', { waitUntil: 'load' });
await page.waitForTimeout(7000);
const before = await page.evaluate(() => { const d = window.__dbg; d.road(-330,160,-330,-60,'stroad4'); d.zone(-330,50,60,'resLow'); d.zone(-330,-20,40,'comLow'); d.run(30); d.save(); const g = window.__game; return { segs: g.net.segs.size, bld: g.buildings.list.size, pop: g.sim.population, zoned: JSON.stringify(g.zones.counts().zoned), money: Math.round(g.sim.money) }; });
console.log('before', before);
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'load' });
await page.waitForTimeout(2500);
await page.click('#continue');
await page.waitForTimeout(8000);
const after = await page.evaluate(() => { const g = window.__game; return { segs: g.net.segs.size, bld: g.buildings.list.size, pop: g.sim.population, zoned: JSON.stringify(g.zones.counts().zoned), money: Math.round(g.sim.money), city: g.cityName }; });
console.log('after', after);
await page.evaluate(() => window.__dbg.view(-330, 60, 380, -1.75, 0.7));
await page.waitForTimeout(1500);
await page.screenshot({ path: 'shots/after-load.png' });
console.log(errs.join('\n'));
await browser.close();
