// Generated by scripts/nametags.mjs from TypeSafe Jev answers (cached in docs/name-tags.json).
// The maps each generated name fits, for names that don't fit all three (street: road name
// starts, suffix: road name endings, commune: the shared commune names). Read if present by
// src/roads/names.ts and src/agents/communes.ts; delete it and every name goes on every map.
import type { MapId } from '../world/maps';

export const NAME_MAPS: Record<string, MapId[]> = {
  "street:Bayou": ['florida'],
  "street:Trout Run": ['appalachia'],
  "street:Hickory Hollow": ['appalachia'],
  "street:Sequoia": ['norcal'],
  "street:Prairie Wind": [],
  "street:Golden Hills": ['norcal'],
  "street:Sawgrass": ['florida'],
  "street:Cattail": ['florida'],
  "street:Bluebonnet": [],
  "suffix:Holler Rd": ['appalachia'],
};
